apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: local
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    config:
      auto.create.topics.enable: "false"
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: 2.7
      inter.broker.protocol.version: 2.7
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
    jvmOptions:
      "-Xmx": 1g
      "-Xms": 1g
    resources:
      limits:
        memory: 1Gi
        cpu: 2
      requests:
        memory: 1Gi
        cpu: 1
    template: {}
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    jvmOptions:
      "-Xmx": 1g
      "-Xms": 1g
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        memory: 1Gi
        cpu: 1
    template: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
