---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-conf
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mqtt-config
    app.kubernetes.io/part-of: mqtt-broker
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    listener 1883 0.0.0.0
    ## Authentication ##
    allow_anonymous true
    password_file /mosquitto/config/password.txt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  namespace: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      nodeSelector:
        node.iotmapper/layer: exit
      containers:
        - name: mosquitto-broker
          image: eclipse-mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 8883
          volumeMounts:
            - name: mosquitto-conf
              mountPath: "/mosquitto/config/mosquitto.conf"
              subPath: "mosquitto.conf"
            - name: mosquitto-secret
              mountPath: "/mosquitto/config/password.txt"
              subPath: "password.txt"
            - name: mosquitto-data
              mountPath: "/mosquitto/data"
            - name: mosquitto-log
              mountPath: "/mosquitto/log"
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mqtt-conf
            items:
              - key: mosquitto.conf
                path: "mosquitto.conf"
        - name: mosquitto-secret
          secret:
            secretName: mqtt-secret
            items:
              - key: password.txt
                path: "password.txt"
        - name: mosquitto-data
          emptyDir: {}
        - name: mosquitto-log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: mqtt
spec:
  selector:
    app: mqtt-broker
  type: NodePort
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
      nodePort: 31883
      name: unsafe
    - port: 8883
      protocol: TCP
      targetPort: 8883
      nodePort: 30883
      name: tls