apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: http-sink-connector2
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: asaintsever.httpsinkconnector.HttpSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: LoRaWAN_Aggregated_Metrics
    camel.source.contentLogLevel: WARN
    camel.sink.contentLogLevel: WARN
    event.batch.maxsize: 1000
    http.endpoint: http://orion-exit-cluster.fiware.svc:1026/v2/op/update?options=keyValues
    http.request.content.type: "application/json"
    errors.tolerance: all
