---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
      nodePort: 30300
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
  type: NodePort
  sessionAffinity: None