---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-input-central
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.12"
  prometheus:
    username: prometheus
    passwordSecretRef:
      name: prometheus-endpoint-password
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        namespace: monitoring
        name: mongodb-admin-secret
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: mongo-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            nodeSelector:
              node.iotmapper/layer: input
            resources:
              requests:
                storage: 5Gi
      template:
        spec:
          nodeSelector:
            node.iotmapper/layer: input
